Fixed unix compilation problems

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9285,6 +9285,87 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for jpeg_CreateDecompress in -ljpeg" >&5
+echo $ECHO_N "checking for jpeg_CreateDecompress in -ljpeg... $ECHO_C" >&6
+if test "${ac_cv_lib_jpeg_jpeg_CreateDecompress+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ljpeg  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char jpeg_CreateDecompress ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+jpeg_CreateDecompress ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_jpeg_jpeg_CreateDecompress=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_jpeg_jpeg_CreateDecompress=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_jpeg_jpeg_CreateDecompress" >&5
+echo "${ECHO_T}$ac_cv_lib_jpeg_jpeg_CreateDecompress" >&6
+if test $ac_cv_lib_jpeg_jpeg_CreateDecompress = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBJPEG 1
+_ACEOF
+
+  LIBS="-ljpeg $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error:
+ASC requires the jpeg library. This library will almost certainly be supplied
+with your distribution. If you have it already installed, perhaps a jpeg-devel
+package is missing.
+If your distribution really does not include the jpeg library, you can get it
+from http://www.ijg.org/ " >&5
+echo "$as_me: error:
+ASC requires the jpeg library. This library will almost certainly be supplied
+with your distribution. If you have it already installed, perhaps a jpeg-devel
+package is missing.
+If your distribution really does not include the jpeg library, you can get it
+from http://www.ijg.org/ " >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+
 echo "$as_me:$LINENO: checking for Mix_PlayChannelTimed in -lSDL_mixer" >&5
 echo $ECHO_N "checking for Mix_PlayChannelTimed in -lSDL_mixer... $ECHO_C" >&6
 if test "${ac_cv_lib_SDL_mixer_Mix_PlayChannelTimed+set}" = set; then
