Fixed configure  Fixed starting map with AI as first player

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -464,7 +464,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all src/physfs"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SGML2MAN DOCBOOK2MAN GENCLL GENCL SDL_CONFIG SDL_CFLAGS SDL_LIBS SDL_TTF_LDADD PKG_CONFIG ac_pt_PKG_CONFIG SIGC_CFLAGS SIGC_LIBS freetype_config EXPAT_INCLUDE EXPAT_LIB EXPAT_SUBDIR LIBEXPAT subdirs PHYSFS_INCLUDE PHYSFS_LIB PHYSFS_SUBDIR LIBPHYSFS FREETYPE_LIBS BOOST_LIBS LIBBZ2 LDADDLIBBZ2 asc_version MAINCONDATA MUSICDIR LIBOBJS LTLIBOBJS PARAGUI_CFLAGS PARAGUI_LIBS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL SGML2MAN DOCBOOK2MAN GENCLL GENCL SDL_CONFIG SDL_CFLAGS SDL_LIBS SDL_TTF_LDADD BOOST_LIBS PKG_CONFIG ac_pt_PKG_CONFIG SIGC_CFLAGS SIGC_LIBS freetype_config EXPAT_INCLUDE EXPAT_LIB EXPAT_SUBDIR LIBEXPAT subdirs PHYSFS_INCLUDE PHYSFS_LIB PHYSFS_SUBDIR LIBPHYSFS FREETYPE_LIBS LIBBZ2 LDADDLIBBZ2 asc_version MAINCONDATA MUSICDIR LIBOBJS LTLIBOBJS PARAGUI_CFLAGS PARAGUI_LIBS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -20786,7 +20786,6 @@ SDL_TTF_LDADD="-lSDL_ttf"
 #AC_MSG_RESULT("yes")
 
 
-
 echo "$as_me:$LINENO: checking for main in -lboost_regex" >&5
 echo $ECHO_N "checking for main in -lboost_regex... $ECHO_C" >&6
 if test "${ac_cv_lib_boost_regex_main+set}" = set; then
@@ -20845,12 +20844,72 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_boost_regex_main" >&5
 echo "${ECHO_T}$ac_cv_lib_boost_regex_main" >&6
 if test $ac_cv_lib_boost_regex_main = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBBOOST_REGEX 1
+  BOOST_LIBS="-lboost_regex"
+else
+  BOOSTERR=yes
+fi
+
+
+if test x$BOOSTERR = xyes ; then
+  echo "$as_me:$LINENO: checking for main in -lboost_regex_gcc" >&5
+echo $ECHO_N "checking for main in -lboost_regex_gcc... $ECHO_C" >&6
+if test "${ac_cv_lib_boost_regex_gcc_main+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lboost_regex_gcc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
 _ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-  LIBS="-lboost_regex $LIBS"
 
+int
+main ()
+{
+main ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_boost_regex_gcc_main=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_boost_regex_gcc_main=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_boost_regex_gcc_main" >&5
+echo "${ECHO_T}$ac_cv_lib_boost_regex_gcc_main" >&6
+if test $ac_cv_lib_boost_regex_gcc_main = yes; then
+  BOOST_LIBS="-lboost_regex_gcc"
 else
   { { echo "$as_me:$LINENO: error:
 ASC requires the Boost library. If you have a distribution supplied
@@ -20863,7 +20922,12 @@ Boost package installed, perhaps the Boost-devel package is missing.
 If your distribution does not include the Boost library, you can get it
 from http://www.boost.org/ " >&2;}
    { (exit 1); exit 1; }; }
+
 fi
+
+fi
+
+
 
 
 
@@ -21910,9 +21974,6 @@ subdirs="$subdirs src/physfs"
 
 
 
-
-
-BOOST_LIBS="-lboost_regex"
 
 
 
@@ -24239,6 +24300,7 @@ s,@SDL_CONFIG@,$SDL_CONFIG,;t t
 s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
 s,@SDL_TTF_LDADD@,$SDL_TTF_LDADD,;t t
+s,@BOOST_LIBS@,$BOOST_LIBS,;t t
 s,@PKG_CONFIG@,$PKG_CONFIG,;t t
 s,@ac_pt_PKG_CONFIG@,$ac_pt_PKG_CONFIG,;t t
 s,@SIGC_CFLAGS@,$SIGC_CFLAGS,;t t
@@ -24254,7 +24316,6 @@ s,@PHYSFS_LIB@,$PHYSFS_LIB,;t t
 s,@PHYSFS_SUBDIR@,$PHYSFS_SUBDIR,;t t
 s,@LIBPHYSFS@,$LIBPHYSFS,;t t
 s,@FREETYPE_LIBS@,$FREETYPE_LIBS,;t t
-s,@BOOST_LIBS@,$BOOST_LIBS,;t t
 s,@LIBBZ2@,$LIBBZ2,;t t
 s,@LDADDLIBBZ2@,$LDADDLIBBZ2,;t t
 s,@asc_version@,$asc_version,;t t
