Added PCX export for maps

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21975,6 +21975,9 @@ echo "$as_me:$LINENO: checking for SIGC" >&5
 echo $ECHO_N "checking for SIGC... $ECHO_C" >&6
 
 if test -n "$PKG_CONFIG"; then
+    if test -n "$SIGC_CFLAGS"; then
+        pkg_cv_SIGC_CFLAGS="$SIGC_CFLAGS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"sigc++-1.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "sigc++-1.2") 2>&5
@@ -21985,10 +21988,14 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 if test -n "$PKG_CONFIG"; then
+    if test -n "$SIGC_LIBS"; then
+        pkg_cv_SIGC_LIBS="$SIGC_LIBS"
+    else
         if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"sigc++-1.2\"") >&5
   ($PKG_CONFIG --exists --print-errors "sigc++-1.2") 2>&5
@@ -21999,38 +22006,59 @@ if test -n "$PKG_CONFIG"; then
 else
   pkg_failed=yes
 fi
+    fi
 else
 	pkg_failed=untried
 fi
 
+
+
 if test $pkg_failed = yes; then
-	SIGC_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "sigc++-1.2"`
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        SIGC_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "sigc++-1.2"`
+        else
+	        SIGC_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "sigc++-1.2"`
+        fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$SIGC_PKG_ERRORS" 1>&5
+	echo "$SIGC_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (sigc++-1.2) were not met.
+	{ { echo "$as_me:$LINENO: error: Package requirements (sigc++-1.2) were not met:
+
+$SIGC_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the SIGC_CFLAGS and SIGC_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&5
-echo "$as_me: error: Package requirements (sigc++-1.2) were not met.
+Alternatively, you may set the environment variables SIGC_CFLAGS
+and SIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (sigc++-1.2) were not met:
+
+$SIGC_PKG_ERRORS
+
 Consider adjusting the PKG_CONFIG_PATH environment variable if you
 installed software in a non-standard prefix.
 
-Alternatively you may set the SIGC_CFLAGS and SIGC_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details." >&2;}
+Alternatively, you may set the environment variables SIGC_CFLAGS
+and SIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
    { (exit 1); exit 1; }; }
 elif test $pkg_failed = untried; then
 	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the SIGC_CFLAGS and SIGC_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables SIGC_CFLAGS
+and SIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
@@ -22038,9 +22066,9 @@ echo "$as_me: error: The pkg-config script could not be found or is too old.  Ma
 is in your PATH or set the PKG_CONFIG environment variable to the full
 path to pkg-config.
 
-Alternatively you may set the SIGC_CFLAGS and SIGC_LIBS environment variables
-to avoid the need to call pkg-config.  See the pkg-config man page for
-more details.
+Alternatively, you may set the environment variables SIGC_CFLAGS
+and SIGC_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
 
 To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
@@ -22048,6 +22076,8 @@ See \`config.log' for more details." >&2;}
 else
 	SIGC_CFLAGS=$pkg_cv_SIGC_CFLAGS
 	SIGC_LIBS=$pkg_cv_SIGC_LIBS
+        echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
 	:
 fi
 
