Merged ASC 1.16.4  Updated water graphics

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -877,6 +877,7 @@ PHYSFS_LIB
 PHYSFS_SUBDIR
 LIBPHYSFS
 FREETYPE_LIBS
+PBPED
 LIBBZ2
 LDADDLIBBZ2
 asc_version
@@ -4414,7 +4415,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4417 "configure"' > conftest.$ac_ext
+  echo '#line 4418 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7373,11 +7374,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7376: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7377: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7380: \$? = $ac_status" >&5
+   echo "$as_me:7381: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7641,11 +7642,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7644: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7645: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7648: \$? = $ac_status" >&5
+   echo "$as_me:7649: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7745,11 +7746,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7748: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7749: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7752: \$? = $ac_status" >&5
+   echo "$as_me:7753: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10186,7 +10187,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10189 "configure"
+#line 10190 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10286,7 +10287,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10289 "configure"
+#line 10290 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12654,11 +12655,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12657: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12661: \$? = $ac_status" >&5
+   echo "$as_me:12662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12758,11 +12759,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12761: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12762: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12765: \$? = $ac_status" >&5
+   echo "$as_me:12766: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14319,11 +14320,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14322: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14323: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14326: \$? = $ac_status" >&5
+   echo "$as_me:14327: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14423,11 +14424,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14426: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14427: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14430: \$? = $ac_status" >&5
+   echo "$as_me:14431: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16642,11 +16643,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16645: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16646: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16649: \$? = $ac_status" >&5
+   echo "$as_me:16650: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16910,11 +16911,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16913: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16914: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16917: \$? = $ac_status" >&5
+   echo "$as_me:16918: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17014,11 +17015,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17017: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17018: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17021: \$? = $ac_status" >&5
+   echo "$as_me:17022: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25429,6 +25430,7 @@ cat >conftest.$ac_ext <<_ACEOF
    void foo( int i ) {};
    void foo( size_t i ) {};
    void foo( unsigned int i ) {};
+   void foo( bool b ) {};
    int main() {
      size_t t = 7;
      foo(t);
@@ -25483,6 +25485,69 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 if test "x$size_t_type" = x ; then
   { echo "$as_me:$LINENO: result: \"no\"" >&5
 echo "${ECHO_T}\"no\"" >&6; }
+
+  { echo "$as_me:$LINENO: checking \"size_t conversion\"" >&5
+echo $ECHO_N "checking \"size_t conversion\"... $ECHO_C" >&6; }
+  cat >conftest.$ac_ext <<_ACEOF
+
+    #include <string>
+    void foo( int i ) {};
+    void foo( unsigned int i ) {};
+    void foo( bool b ) {};
+    int main() {
+       size_t t = 7;
+       foo(t);
+       return 0;
+    }
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  { echo "$as_me:$LINENO: result: \"yes\"" >&5
+echo "${ECHO_T}\"yes\"" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ { echo "$as_me:$LINENO: error: \"Failed to compile size_t distinction check. Please contact bugs@asc-hq.org \"" >&5
+echo "$as_me: error: \"Failed to compile size_t distinction check. Please contact bugs@asc-hq.org \"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
 else
   CXXFLAGS="$CXXFLAGS -DSIZE_T_not_identical_to_INT"
   { echo "$as_me:$LINENO: result: \"yes\"" >&5
@@ -25490,49 +25555,43 @@ echo "${ECHO_T}\"yes\"" >&6; }
 fi
 
 
-
-
-
-
-
-
-
-
-{ echo "$as_me:$LINENO: checking \"data files\"" >&5
-echo $ECHO_N "checking \"data files\"... $ECHO_C" >&6; }
-missingdata=`./checkfordata.pl data/buildings.con data/mk1.con data/trrobj.con data/trrobj2.con data/units-mk3.con`
-if test "x$missingdata" = x ; then
-  { echo "$as_me:$LINENO: result: \"yes\"" >&5
-echo "${ECHO_T}\"yes\"" >&6; }
+{ echo "$as_me:$LINENO: checking for \"source/unix/pbpedit/pbpeditor.cpp\"" >&5
+echo $ECHO_N "checking for \"source/unix/pbpedit/pbpeditor.cpp\"... $ECHO_C" >&6; }
+if test "${ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  { echo "$as_me:$LINENO: result: \"no\"" >&5
-echo "${ECHO_T}\"no\"" >&6; }
-  { { echo "$as_me:$LINENO: error:
-The following data files could not be found: $missingdata .
-If you got the ASC source from CVS it is absolutely normal that this error
-occurs, since many data files are not managed with CVS.
-
-These files must be downloaded separately. This can be done automatically by
-calling the ./getdata script , or you can get them manually from
-http://www.asc-hq.org/download_updates.html
- " >&5
-echo "$as_me: error:
-The following data files could not be found: $missingdata .
-If you got the ASC source from CVS it is absolutely normal that this error
-occurs, since many data files are not managed with CVS.
-
-These files must be downloaded separately. This can be done automatically by
-calling the ./getdata script , or you can get them manually from
-http://www.asc-hq.org/download_updates.html
- " >&2;}
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
+if test -r ""source/unix/pbpedit/pbpeditor.cpp""; then
+  ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_=yes
+else
+  ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_=no
 fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_" >&5
+echo "${ECHO_T}$ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_" >&6; }
+if test $ac_cv_file__source_unix_pbpedit_pbpeditor_cpp_ = yes; then
+  PBPED=pbpedit
+fi
+
+
+
+
+
+
+
+
+
+
+
 
 
 
 MAINCONDATA="palette.pal data.version title.jpg title_mapeditor.jpg \
 progress.* smalaril.fnt usablack.fnt arial8.fnt \
-msystem.fnt gui.fnt guicol.fnt monogui.fnt sounds.asctxt \
+msystem.fnt gui.fnt guicol.fnt monogui.fnt \
 height2.raw windp.raw windpfei.raw farbe.raw \
 allianc.raw weapicon.raw expicons.raw hexinvi2.raw \
 hexinvis.raw fg8.raw windrose.raw hexfld_a.raw \
@@ -25546,18 +25605,11 @@ windpowr.raw solarpwr.raw ammotran.raw research.raw \
 pwrplant.raw bldinfo.raw mining.raw tabmark.raw \
 traninfo.raw attack.raw hexfeld.raw mapbkgr.raw \
 hex2oct.raw weapinfo.raw amatur.raw hxborder.raw \
-leergui.raw guiremov.raw  *.tec \
+leergui.raw guiremov.raw  \
 hexmines.raw curshex2.raw markedfield.pcx curshex.raw \
-railstations2.map cancel.nic poweron.nic poweroff.nic \
-extload.nic consttnk.nic reacfoff.nic reacfire.nic \
-loading.nic viewmap.nic dig.nic abriss.nic \
-building.nic refueld.nic refuel.nic repair.nic \
-buildany.nic remomine.nic moormine.nic floatmin.nic \
-persmine.nic tankmine.nic putmine.nic endturn.nic \
-informat.nic ascent.nic descent.nic attack.nic \
-movement.nic *.nic 640480.pcx *.raw *.scr *.fnt \
+railstations2.map *.raw *.fnt \
 *.dat *.map helpsys?.txt message?.txt *.pcx lcac2.jpg \
-bkgr4.scr *.wav *.gif *.asctxt"
+*.gif *.asctxt *.gfx"
 
 
 
@@ -25575,9 +25627,8 @@ fi
 
 
 
+ac_config_files="$ac_config_files Makefile asc.spec doc/Makefile doc/manpages/Makefile source/Makefile source/ai/Makefile source/clparser/Makefile source/docs/Makefile source/docs/en/Makefile source/graphics/Makefile source/dialogs/Makefile source/widgets/Makefile source/actions/Makefile source/libs/Makefile source/libs/sdlmm/Makefile source/libs/sdlmm/src/Makefile source/libs/triangul/Makefile source/libs/loki/Makefile source/libs/paragui/Makefile source/libs/paragui/src/Makefile source/libs/paragui/src/widgets/Makefile source/libs/paragui/src/core/Makefile source/libs/paragui/src/draw/Makefile source/libs/paragui/src/font/Makefile source/libs/paragui/src/themes/Makefile source/libs/paragui/src/ystring/Makefile source/sdl/Makefile source/tools/Makefile source/tools/lib/Makefile source/tools/linux/Makefile source/unix/Makefile source/unix/mapeditor/Makefile source/unix/pbpedit/Makefile source/unix/asc/Makefile data/Makefile data/buildings/Makefile data/trrobj/Makefile data/trrobj2/Makefile data/units/Makefile data/units/MK1/Makefile data/units/MK3/Makefile data/dialog/Makefile data/music/Makefile"
 
-
-ac_config_files="$ac_config_files Makefile asc.spec doc/Makefile doc/manpages/Makefile source/Makefile source/ai/Makefile source/clparser/Makefile source/docs/Makefile source/docs/en/Makefile source/graphics/Makefile source/dialogs/Makefile source/widgets/Makefile source/actions/Makefile source/libs/Makefile source/libs/sdlmm/Makefile source/libs/sdlmm/src/Makefile source/libs/triangul/Makefile source/libs/loki/Makefile source/libs/paragui/Makefile source/libs/paragui/src/Makefile source/libs/paragui/src/widgets/Makefile source/libs/paragui/src/core/Makefile source/libs/paragui/src/draw/Makefile source/libs/paragui/src/font/Makefile source/libs/paragui/src/themes/Makefile source/libs/paragui/src/ystring/Makefile source/sdl/Makefile source/tools/Makefile source/tools/lib/Makefile source/tools/linux/Makefile source/unix/Makefile source/unix/mapeditor/Makefile source/unix/asc/Makefile data/Makefile data/dialog/Makefile data/music/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -26204,8 +26255,15 @@ do
     "source/tools/linux/Makefile") CONFIG_FILES="$CONFIG_FILES source/tools/linux/Makefile" ;;
     "source/unix/Makefile") CONFIG_FILES="$CONFIG_FILES source/unix/Makefile" ;;
     "source/unix/mapeditor/Makefile") CONFIG_FILES="$CONFIG_FILES source/unix/mapeditor/Makefile" ;;
+    "source/unix/pbpedit/Makefile") CONFIG_FILES="$CONFIG_FILES source/unix/pbpedit/Makefile" ;;
     "source/unix/asc/Makefile") CONFIG_FILES="$CONFIG_FILES source/unix/asc/Makefile" ;;
     "data/Makefile") CONFIG_FILES="$CONFIG_FILES data/Makefile" ;;
+    "data/buildings/Makefile") CONFIG_FILES="$CONFIG_FILES data/buildings/Makefile" ;;
+    "data/trrobj/Makefile") CONFIG_FILES="$CONFIG_FILES data/trrobj/Makefile" ;;
+    "data/trrobj2/Makefile") CONFIG_FILES="$CONFIG_FILES data/trrobj2/Makefile" ;;
+    "data/units/Makefile") CONFIG_FILES="$CONFIG_FILES data/units/Makefile" ;;
+    "data/units/MK1/Makefile") CONFIG_FILES="$CONFIG_FILES data/units/MK1/Makefile" ;;
+    "data/units/MK3/Makefile") CONFIG_FILES="$CONFIG_FILES data/units/MK3/Makefile" ;;
     "data/dialog/Makefile") CONFIG_FILES="$CONFIG_FILES data/dialog/Makefile" ;;
     "data/music/Makefile") CONFIG_FILES="$CONFIG_FILES data/music/Makefile" ;;
 
@@ -26436,6 +26494,7 @@ PHYSFS_LIB!$PHYSFS_LIB$ac_delim
 PHYSFS_SUBDIR!$PHYSFS_SUBDIR$ac_delim
 LIBPHYSFS!$LIBPHYSFS$ac_delim
 FREETYPE_LIBS!$FREETYPE_LIBS$ac_delim
+PBPED!$PBPED$ac_delim
 LIBBZ2!$LIBBZ2$ac_delim
 LDADDLIBBZ2!$LDADDLIBBZ2$ac_delim
 asc_version!$asc_version$ac_delim
@@ -26445,7 +26504,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
