Fixed compilation problems

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11180,6 +11180,61 @@ echo "${ECHO_T}\"yes\"" >&6
 fi
 
 
+echo "$as_me:$LINENO: checking \"broken std::vector\"" >&5
+echo $ECHO_N "checking \"broken std::vector\"... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <vector>
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+
+      std::vector<int> s;
+      s.push_back(1);
+      s.at(0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+stdvector_broken=yes
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+
+if test "x$stdvector_broken" = x ; then
+  echo "$as_me:$LINENO: result: \"no\"" >&5
+echo "${ECHO_T}\"no\"" >&6
+else
+  CXXFLAGS="$CXXFLAGS -D_vector_at_broken_"
+  echo "$as_me:$LINENO: result: \"yes\"" >&5
+echo "${ECHO_T}\"yes\"" >&6
+fi
+
+
+
 
 
 
