Fixed crash on error handling  Improved configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25613,16 +25613,90 @@ railstations2.map *.raw *.fnt \
 
 
 
-{ echo "$as_me:$LINENO: checking \"music files\"" >&5
-echo $ECHO_N "checking \"music files\"... $ECHO_C" >&6; }
-missingmusic=`./checkfordata.pl data/music/frontiers.ogg data/music/time_to_strike.ogg data/music/machine_wars.ogg`
-if test "x$missingmusic" = x ; then
-  { echo "$as_me:$LINENO: result: \"yes\"" >&5
-echo "${ECHO_T}\"yes\"" >&6; }
-  MUSICDIR=music
+{ echo "$as_me:$LINENO: checking for data/music/frontiers.ogg" >&5
+echo $ECHO_N "checking for data/music/frontiers.ogg... $ECHO_C" >&6; }
+if test "${ac_cv_file_data_music_frontiers_ogg+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  { echo "$as_me:$LINENO: result: \"no\"" >&5
-echo "${ECHO_T}\"no\"" >&6; }
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "data/music/frontiers.ogg"; then
+  ac_cv_file_data_music_frontiers_ogg=yes
+else
+  ac_cv_file_data_music_frontiers_ogg=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file_data_music_frontiers_ogg" >&5
+echo "${ECHO_T}$ac_cv_file_data_music_frontiers_ogg" >&6; }
+if test $ac_cv_file_data_music_frontiers_ogg = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DATA_MUSIC_FRONTIERS_OGG 1
+_ACEOF
+
+
+else
+  missingmusic=x
+fi
+{ echo "$as_me:$LINENO: checking for data/music/time_to_strike.ogg" >&5
+echo $ECHO_N "checking for data/music/time_to_strike.ogg... $ECHO_C" >&6; }
+if test "${ac_cv_file_data_music_time_to_strike_ogg+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "data/music/time_to_strike.ogg"; then
+  ac_cv_file_data_music_time_to_strike_ogg=yes
+else
+  ac_cv_file_data_music_time_to_strike_ogg=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file_data_music_time_to_strike_ogg" >&5
+echo "${ECHO_T}$ac_cv_file_data_music_time_to_strike_ogg" >&6; }
+if test $ac_cv_file_data_music_time_to_strike_ogg = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DATA_MUSIC_TIME_TO_STRIKE_OGG 1
+_ACEOF
+
+
+else
+  missingmusic=x
+fi
+{ echo "$as_me:$LINENO: checking for data/music/machine_wars.ogg" >&5
+echo $ECHO_N "checking for data/music/machine_wars.ogg... $ECHO_C" >&6; }
+if test "${ac_cv_file_data_music_machine_wars_ogg+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "data/music/machine_wars.ogg"; then
+  ac_cv_file_data_music_machine_wars_ogg=yes
+else
+  ac_cv_file_data_music_machine_wars_ogg=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file_data_music_machine_wars_ogg" >&5
+echo "${ECHO_T}$ac_cv_file_data_music_machine_wars_ogg" >&6; }
+if test $ac_cv_file_data_music_machine_wars_ogg = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_DATA_MUSIC_MACHINE_WARS_OGG 1
+_ACEOF
+
+
+else
+  missingmusic=x
+fi
+
+if test "x$missingmusic" != xx ; then
+  MUSICDIR=music
 fi
 
 
@@ -27298,11 +27372,11 @@ fi
 
 
 
-if test "x$missingmusic" != x ; then
+if test "x$missingmusic" == xx ; then
   { echo "$as_me:$LINENO: WARNING:
-The following music files could not be found: $missingmusic .
-The music files are not distributed together with the source code because
-of their size. ASC can run without the music files being present, this message
+The music files could not be found. These are not distributed together with the
+source code because of their size.
+ASC can run without the music files being present, this message
 is just to inform you about the existence of the music.
 
 You can download the music files by calling the ./getmusic script and
@@ -27311,9 +27385,9 @@ Alternatively, you can download and install them manually anytime later,
 which is described in the documentation.
  " >&5
 echo "$as_me: WARNING:
-The following music files could not be found: $missingmusic .
-The music files are not distributed together with the source code because
-of their size. ASC can run without the music files being present, this message
+The music files could not be found. These are not distributed together with the
+source code because of their size.
+ASC can run without the music files being present, this message
 is just to inform you about the existence of the music.
 
 You can download the music files by calling the ./getmusic script and
