Improved checks for SDL_sound

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21113,7 +21113,7 @@ fi
 
 
 
-
+AdditionalIncludeDir=""
 gcc296test=yes
 # Check whether --enable-gcc296-detection was given.
 if test "${enable_gcc296_detection+set}" = set; then
@@ -22199,6 +22199,351 @@ If your distribution does not include the SDL_sound library, you can get it
 from http://www.icculus.org/SDL_sound/ " >&2;}
    { (exit 1); exit 1; }; }
 fi
+
+
+
+OLDCPPFLAGS=$CPPFLAGS
+
+CPPFLAGS="$CPPFLAGS $SDL_CFLAGS"
+
+if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for SDL_sound.h" >&5
+echo $ECHO_N "checking for SDL_sound.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_SDL_sound_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_sound_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking SDL_sound.h usability" >&5
+echo $ECHO_N "checking SDL_sound.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <SDL_sound.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking SDL_sound.h presence" >&5
+echo $ECHO_N "checking SDL_sound.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <SDL_sound.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: SDL_sound.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: SDL_sound.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: SDL_sound.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: SDL_sound.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: SDL_sound.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: SDL_sound.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL_sound.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: SDL_sound.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for SDL_sound.h" >&5
+echo $ECHO_N "checking for SDL_sound.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_SDL_sound_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_SDL_sound_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_sound_h" >&6; }
+
+fi
+if test $ac_cv_header_SDL_sound_h = yes; then
+  :
+else
+  SDLSOUNDHEADER=no
+fi
+
+
+if test "X$SDLSOUNDHEADER" = "Xno" ; then
+  CFLAGS="$CFLAGS -I/usr/local/include/SDL"
+  CPPFLAGS="$CPPFLAGS -I/usr/local/include/SDL"
+  if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for SDL_sound.h" >&5
+echo $ECHO_N "checking for SDL_sound.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_SDL_sound_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_sound_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking SDL_sound.h usability" >&5
+echo $ECHO_N "checking SDL_sound.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <SDL_sound.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking SDL_sound.h presence" >&5
+echo $ECHO_N "checking SDL_sound.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <SDL_sound.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: SDL_sound.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: SDL_sound.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: SDL_sound.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: SDL_sound.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: SDL_sound.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: SDL_sound.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SDL_sound.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SDL_sound.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: SDL_sound.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for SDL_sound.h" >&5
+echo $ECHO_N "checking for SDL_sound.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_SDL_sound_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_SDL_sound_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_SDL_sound_h" >&5
+echo "${ECHO_T}$ac_cv_header_SDL_sound_h" >&6; }
+
+fi
+if test $ac_cv_header_SDL_sound_h = yes; then
+  :
+else
+  SDLSOUNDHEADER2=no
+fi
+
+
+  if test "X$SDLSOUNDHEADER2" = "Xno" ; then
+     { { echo "$as_me:$LINENO: error:
+Could not locate the the SDL_sound.h header file. Make sure it is available
+and add its search path to the CPPFLAGS
+Example:
+   export CPPFLAGS=-I/my/include/directory
+   ./configure
+     " >&5
+echo "$as_me: error:
+Could not locate the the SDL_sound.h header file. Make sure it is available
+and add its search path to the CPPFLAGS
+Example:
+   export CPPFLAGS=-I/my/include/directory
+   ./configure
+     " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+     AdditionalIncludeDir="$AdditionalIncludeDir -I/usr/local/include/SDL/"
+     CFLAGS="$CFLAGS $AdditionalIncludeDir"
+  fi
+fi
+
+CPPFLAGS=$OLDCPPFLAGS
 
 
 
@@ -23546,10 +23891,10 @@ subdirs="$subdirs src/physfs"
 
 
 
-CXXFLAGS="$SAVE_CXXFLAGS $FREETYPE_CFLAGS"
+CXXFLAGS="$SAVE_CXXFLAGS $FREETYPE_CFLAGS $AdditionalIncludeDir"
 
 
-CFLAGS=$SAVE_CFLAGS
+CFLAGS="$SAVE_CFLAGS $AdditionalIncludeDir"
 LIBS=$SAVE_LIBS
 
 
