added g++ check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21351,6 +21351,11 @@ fi
 
 
 
+if test x$CXX = x; then
+   { { echo "$as_me:$LINENO: error: No C++ compiler found! Please install it. The package is typcially 'g++' " >&5
+echo "$as_me: error: No C++ compiler found! Please install it. The package is typcially 'g++' " >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
